In [17]:
from datetime import datetime
import pandas as pd

_tdy = datetime.today().strftime("%Y-%m-%d")

out = pd.read_csv(f"../results/{_tdy}/tickets/ticket_safe.csv")

In [18]:
out

,player,team,opp,is_home,game_date,stat_name,pred_mean,baseline_mean,delta_mean,p_over,matchup
0,Jamal Murray,DEN,BOS,1,2026-02-25,fg3,2.136711,0.0,2.136711,0.629735,DEN vs BOS
1,Nikola Jokić,DEN,BOS,1,2026-02-25,reb,11.956206,0.0,11.956206,0.998697,DEN vs BOS
2,Victor Wembanyama,SAS,TOR,0,2026-02-25,reb,9.944473,0.0,9.944473,0.996305,SAS @ TOR
3,Jarrett Allen,CLE,MIL,0,2026-02-25,reb,9.503982,0.0,9.503982,0.995314,CLE @ MIL
4,Chet Holmgren,OKC,DET,0,2026-02-20,reb,9.091206,0.0,9.091206,0.994126,OKC @ DET
5,Dylan Cardwell(TW),SAC,HOU,0,2026-02-20,reb,9.046206,0.0,9.046206,0.993979,SAC @ HOU
6,Jalen Duren,DET,OKC,1,2026-02-25,reb,8.693706,0.0,8.693706,0.992678,DET vs OKC
7,Neemias Queta,BOS,DEN,0,2026-02-20,reb,8.686206,0.0,8.686206,0.992647,BOS @ DEN
8,Alperen Şengün,HOU,SAC,1,2026-02-20,reb,8.556973,0.0,8.556973,0.992096,HOU vs SAC
9,Scottie Barnes,TOR,SAS,1,2026-02-20,reb,7.763706,0.0,7.763706,0.987598,TOR vs SAS

In [24]:
from datetime import datetime
import pandas as pd

_tdy = datetime.today().strftime("%Y-%m-%d")

out = pd.read_csv(f"../results/{_tdy}/tickets/ticket_ceiling.csv")
out[["player", 'team',"stat_name", "pred_mean"]]

               player team stat_name  pred_mean
0        Jamal Murray  DEN       fg3   2.136711
1       Derrick White  BOS       fg3   2.908558
2        Nikola Jokić  DEN       reb  11.956206
3   Victor Wembanyama  SAS       reb   9.944473
4       Jarrett Allen  CLE       reb   9.503982
5       Chet Holmgren  OKC       reb   9.091206
6  Dylan Cardwell(TW)  SAC       reb   9.046206
7         Jalen Duren  DET       reb   8.693706
8       Neemias Queta  BOS       reb   8.686206
9      Alperen Şengün  HOU       reb   8.556973

In [25]:
from datetime import datetime
import pandas as pd

_tdy = datetime.today().strftime("%Y-%m-%d")

out = pd.read_csv(f"../results/{_tdy}/tickets/ticket_balanced.csv")
out[["player", 'team',"stat_name", "pred_mean"]]

               player team stat_name  pred_mean
0        Jamal Murray  DEN       fg3   2.136711
1       Derrick White  BOS       fg3   2.908558
2        Nikola Jokić  DEN       reb  11.956206
3   Victor Wembanyama  SAS       reb   9.944473
4       Jarrett Allen  CLE       reb   9.503982
5       Chet Holmgren  OKC       reb   9.091206
6  Dylan Cardwell(TW)  SAC       reb   9.046206
7         Jalen Duren  DET       reb   8.693706
8       Neemias Queta  BOS       reb   8.686206
9      Alperen Şengün  HOU       reb   8.556973

In [26]:
from datetime import datetime
import pandas as pd

_tdy = datetime.today().strftime("%Y-%m-%d")

out = pd.read_csv(f"../results/{_tdy}/tickets/ticket_top5_per_stat.csv")
out[["player", 'team',"stat_name", "pred_mean"]]

                 player team stat_name  pred_mean
0          Jamal Murray  DEN       fg3   2.136711
1         Derrick White  BOS       fg3   2.908558
2     Russell Westbrook  SAC       fg3   2.594781
3      Jabari Smith Jr.  HOU       fg3   1.518217
4       Duncan Robinson  DET       fg3   2.421509
5         DeMar DeRozan  SAC       pts   7.458811
6   Dorian Finney-Smith  HOU       pts   7.204760
7         Kyle Anderson  MEM       pts  10.754084
8            Tari Eason  HOU       pts   8.740782
9            Kyle Kuzma  MIL       pts   6.009426
10         Nikola Jokić  DEN       reb  11.956206
11         Nikola Jokić  DEN       reb  11.506206
12    Victor Wembanyama  SAS       reb   9.944473
13    Victor Wembanyama  SAS       reb   9.938706
14        Jarrett Allen  CLE       reb   9.503982